trigger:
    - master
  
pool:
  vmImage: 'ubuntu-20.04'

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-umgccaps'
    repository: 'umgccaps/advance-development-factory-formbot-dialogflow'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  condition: and(succeeded(), eq(variables.isMain, true))
  inputs:
    containerRegistry: 'dockerhub-umgccaps'
    command: 'login'

- task: Docker@2
  condition: and(succeeded(), eq(variables.isMain, true))
  inputs:
    containerRegistry: 'dockerhub-umgccaps'
    repository: 'umgccaps/advance-development-factory-formbot-dialogflow'
    command: 'push'

- task: CopyFiles@2
  condition: and(succeeded(), eq(variables.isMain, true))
  inputs:
    Contents: 'deployment.azure.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables.isMain, true))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'