trigger:
    - master
  
pool:
  vmImage: 'ubuntu-20.04'

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

steps:
- task: CmdLine@2
  inputs:
    script: 'make build-env' 

- task: CmdLine@2
  condition: and(succeeded(), eq(variables.isMain, true))
  inputs:
    script: 'docker login $(HOST) -u $(USERNAME) -p $(PASSWORD)'
    
- task: CmdLine@2
  condition: and(succeeded(), eq(variables.isMain, true))
  inputs:
    script: 'make push'
      
      